### PR TITLE
Logistic regression for politeness strategies

### LINKED ISSUE #82: Rerun logistic regression for politeness scores
@sophieball  check if the code still works on new data format

### PR DESCRIPTION
**Pull request by sophieball**
Instructions:
0. Make sure you have SE_words.list, otherwise, run `python src/find_SE_words.py`
1. Run with bazel `main/politeness_logi`. Note that it awaits data from your other R code
2. The results will be in bazel's folder: `politeness_features.csv`,  `politeness_logi.out`. Please move these two files out
3. We want to keep `politeness_features.csv` so that we could rerun `politeness_logi.R` if necessary
4. We'll use results in `politeness_logi.out` to determine what features we use in the classifier

Fixes #82

### CODE REVIEW

**Comment by CaptainEmerson** [comment]
I did a step 0: "bazel build src:convo_politeness". When I ran step 1, I got:

```
/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/util.py:271: UserWarning: [W031] Model 'en_core_web_md' (3.0.0) requires spaCy v3.0 and is incompatible with the current spaCy version (2.3.0). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/__main__/src/convo_politeness.py", line 5, in <module>
    download_data.download_data()
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/__main__/src/download_data.py", line 36, in download_data
    spacy.load("en_core_web_md")
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/util.py", line 170, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/util.py", line 191, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/google/home/emersonm/.local/lib/python3.8/site-packages/en_core_web_md/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/util.py", line 235, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/util.py", line 216, in load_model_from_path
    component = nlp.create_pipe(factory, config=config)
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/language.py", line 307, in create_pipe
    raise KeyError(Errors.E002.format(name=name))
KeyError: "[E002] Can't find factory for 'tok2vec'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['tok2vec']` or remove it from the model meta and add it via `nlp.add_pipe` instead."
Error in eval(predvars, data, env) : object 'label' not found
Calls: glm ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
Execution halted
```

**Comment by sophieball** [comment]
I made some changes, which might solve the problem.

**Comment by CaptainEmerson** [comment]
Hmm. Now I get:

```
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/__main__/src/convo_politeness.py", line 4, in <module>
    from src import download_data
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/__main__/src/download_data.py", line 6, in <module>
    import spacy
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__spacy/spacy/__init__.py", line 10, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
ImportError: cannot import name 'prefer_gpu' from 'thinc.api' (/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/deps/pypi__thinc/thinc/api.py)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: read.csv -> read.table
Execution halted

```

**Comment by CaptainEmerson** [comment]
Oh, I see [we've encountered this before](https://github.com/sophieball/toxicity-detector/pull/93#issuecomment-775424463). Will try that solution.

**Comment by CaptainEmerson** [comment]
```
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/__main__/src/convo_politeness.py", line 23, in <module>
    from src import text_parser
ImportError: cannot import name 'text_parser' from 'src' (/usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/execroot/__main__/bazel-out/k8-fastbuild/bin/src/convo_politeness.runfiles/__main__/src/__init__.py)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
Calls: read.csv -> read.table
Execution halted

```

**Comment by CaptainEmerson** [comment]
Oops, in the prior one, I hadn't built the right binary. Trying to build the right binary:

```
bazel build main:politeness_logi 
INFO: Analyzed target //main:politeness_logi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/emersonm/.cache/bazel/_bazel_emersonm/944306df6cbfee92be3237efb3eb9146/external/R_readr/BUILD.bazel:10:6: Building R package readr failed: (Exit 1): build.sh failed: error executing command external/com_grail_rules_r/R/scripts/build.sh

...

*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘readr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/tmp/bazel/R/lib_readr/readr/libs/readr.so':
  /usr/grte/v4/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/bazel/R/lib_readr/readr/libs/readr.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/tmp/bazel/R/lib_readr/readr’
Target //main:politeness_logi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 142.866s, Critical Path: 142.41s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

```

**Comment by sophieball** [comment]
` /usr/grte/v4/lib64/libm.so.6: version 'GLIBC_2.29' not found (required by /tmp/bazel/R/lib_readr/readr/libs/readr.so)`

`GLIBC` seems to be something you need to install on your machine:
https://www.digitalocean.com/community/questions/how-install-glibc-2-29-or-higher-in-ubuntu-18-04

**Comment by CaptainEmerson** [comment]
I seem to already have a newer version:
`libc6 is already the newest version (2.31-9+build1).`

**Comment by sophieball** [comment]
Do you have library `readr` in your R?

**Comment by CaptainEmerson** [comment]
Yes, readr_1.3.1

**Comment by sophieball** [comment]
@CaptainEmerson Can you give it a try now?

**Comment by CaptainEmerson** [comment]
Same issue:
```
Error: package or namespace load failed for ‘readr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/tmp/bazel/R/lib_readr/readr/libs/readr.so':
  /usr/grte/v4/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/bazel/R/lib_readr/readr/libs/readr.so)
```

**Comment by sophieball** [comment]
We aren't using this

**Pull request closed without merging**
