### PR TITLE
Ngram plot font

### PR DESCRIPTION
**Pull request by sophieball**
Instructions:
Execute `src/convo_word_freq_diff`

### CODE REVIEW

**Comment by CaptainEmerson** [comment]
Same error as #95 and #96

**Comment by sophieball** [comment]
> Same error as #95 and #96

I think it's some library updates that made spacy middle-size English set somehow unusable.. I replaced it by the small set

**Comment by CaptainEmerson** [comment]
Looks like I'm over that error. Yay! Did you propigate the change to the other open PRs? Seems like I can test those in parallel.

But for this PR, I've run the code like this:
```
> system2("Rscript", "src/convo_word_freq_diff", input = format_csv(df))
Error: unexpected input in "from _"
Execution halted
```

Ideas?

**Comment by CaptainEmerson** [comment]
Ok, that just silliness on my part --- I'm not sure why I thought `Rscript src/convo_word_freq_diff` was going to work.

**Review by CaptainEmerson — APPROVED** [review]

**Pull request merged**
