### PR TITLE
analyze 1-6-grams

### PR DESCRIPTION
**Pull request by sophieball**
also saves everything into csvs

#66

### CODE REVIEW

**Comment by CaptainEmerson** [comment]
```
> system2("bazel-bin/src/convo_word_freq_diff", input = format_csv(df))
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/__main__/src/convo_word_freq_diff.py", line 12, in <module>
    from convokit import Corpus, Speaker, Utterance
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__convokit_2_3_2_4/convokit/__init__.py", line 4, in <module>
    from .politenessStrategies import *
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__convokit_2_3_2_4/convokit/politenessStrategies/__init__.py", line 1, in <module>
    from .politenessStrategies import *
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__convokit_2_3_2_4/convokit/politenessStrategies/politenessStrategies.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
> 
```

**Comment by sophieball** [comment]
I removed plotting - it's not necessary here

**Comment by CaptainEmerson** [comment]
```
(myproject) emersonm@emersonm:~/toxicity-detector$ git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 788 bytes | 43.00 KiB/s, done.
From https://github.com/sophieball/toxicity-detector
   4f9679f..790fed2  G-ngrams-csv -> origin/G-ngrams-csv
Updating 4f9679f..790fed2
Fast-forward
 src/BUILD                   | 63 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 src/convo_word_freq_diff.py | 31 +++++++------------------------
 2 files changed, 68 insertions(+), 26 deletions(-)
(myproject) emersonm@emersonm:~/toxicity-detector$ bazel build src:convo_word_freq_diff 
Starting local Bazel server and connecting to it...
INFO: Analyzed target //src:convo_word_freq_diff (56 packages loaded, 6969 targets configured).
INFO: Found 1 target...
Target //src:convo_word_freq_diff up-to-date:
  bazel-bin/src/convo_word_freq_diff
INFO: Elapsed time: 5.985s, Critical Path: 0.18s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
(myproject) emersonm@emersonm:~/toxicity-detector$ fg
R


> system2("bazel-bin/src/convo_word_freq_diff", input = format_csv(df))
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/__main__/src/convo_word_freq_diff.py", line 12, in <module>
    from convokit import Corpus, Speaker, Utterance
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__convokit_2_3_2_4/convokit/__init__.py", line 4, in <module>
    from .politenessStrategies import *
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__convokit_2_3_2_4/convokit/politenessStrategies/__init__.py", line 1, in <module>
    from .politenessStrategies import *
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__convokit_2_3_2_4/convokit/politenessStrategies/politenessStrategies.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/deps_pypi__matplotlib_3_3_0/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
> 

```

**Comment by CaptainEmerson** [comment]
This looks like a minor issue:
```
Vocab size is 3201
Comparing language...
ngram zscores computed.
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/__main__/src/convo_word_freq_diff.py", line 117, in <module>
    word_freq(corpus)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/src/convo_word_freq_diff.runfiles/__main__/src/convo_word_freq_diff.py", line 52, in word_freq
    .format("bazel-bin" + os.getcwd().split("/bin")[1]))
IndexError: list index out of range 
```

**Pull request merged**
