### PR TITLE
stratified split and hyper parameter tuning

### LINKED ISSUE #55: Stratified  sampling for cross validation
Naveen implemented his version of this but it was still a bit different - 

Since the ratio between 0's and 1's are very skewed, if each time we randomly sample a subset to do cross validation (`KFold` in sklearn), sometimes we might end up with only 0's. I've replaced `KFold` with `StratifiedKFold` so the ratio between 0's and 1's will be preserved. Also I've added back the hyper-parameter tuning.

```INFO:root:Best parameter: SVC(C=10, gamma=2.5, kernel='sigmoid'), ratio: 10.
INFO:root:Best score: 0.9182937270873832.
INFO:root:Removing angry words towards oneself and SE words.
INFO:root:Crossvalidation score after adjustment is
              precision    recall  f1-score   support

         0.0       0.94      0.99      0.97      1099
         1.0       0.78      0.34      0.47       103

    accuracy                           0.94      1202
   macro avg       0.86      0.67      0.72      1202
weighted avg       0.93      0.94      0.92      1202
```

### PR DESCRIPTION
**Pull request by sophieball**
Code update for #55 

I also deleted the unused functions. Their names are so similar that I often write to the wrong function.

### CODE REVIEW

**Comment by CaptainEmerson** [comment]
Is this error related?

```
> system2("bazel-bin/main/train_classifier_g",
+         input = format_csv(df))
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 3, in <module>
    download_data.download_data()
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/download_data.py", line 31, in download_data
    spacy.load("en")
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__spacy_2_2_4/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__spacy_2_2_4/spacy/util.py", line 163, in load_model
    if is_package(name):  # installed as package
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__spacy_2_2_4/spacy/util.py", line 256, in is_package
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
> 

```

**Comment by sophieball** [comment]
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

I added `setuptools` in `requirements.txt`

**Comment by CaptainEmerson** [comment]
```
> system2("bazel-bin/main/train_classifier_g",
+         input = format_csv(df))
⚠ Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.
/usr/local/google/home/emersonm/myproject/bin/python3: No module named pip
> 

```

**Comment by sophieball** [comment]
I also have the `Skipping` message. But why it's complaining about `pip`?

**Comment by CaptainEmerson** [comment]
I got this the first time I ran it:
```

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_md')
Traceback (most recent call last):
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/main/train_classifier_g.py", line 12, in <module>
    from src import suite
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/suite.py", line 17, in <module>
    from src import create_features
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/create_features.py", line 7, in <module>
    from src import text_modifier
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/__main__/src/text_modifier.py", line 12, in <module>
    nlp = spacy.load("en_core_web_md", disable=["parser", "ner"])
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__spacy_2_2_4/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/usr/local/google/home/emersonm/toxicity-detector/bazel-bin/main/train_classifier_g.runfiles/deps_pypi__spacy_2_2_4/spacy/util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

But it seemed to work the second time.

**Pull request merged**
